// This file is auto-generated by @hey-api/openapi-ts

export const $Code = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-03-17T12:53:08.624Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-03-17T12:53:08.624Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        code: {
            type: 'string',
            example: 'ABC123XYZ'
        },
        code_used_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        opt_in_communications: {
            type: 'integer',
            minimum: 0,
            maximum: 1,
            example: 0
        },
        opt_in_communications_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        code_batch_id: {
            type: 'string',
            format: 'uuid',
            example: '1234567890'
        },
        code_used_by_id: {
            type: 'number',
            nullable: true
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'code', 'code_used_at', 'opt_in_communications', 'opt_in_communications_at', 'code_batch_id', 'code_used_by_id']
} as const;

export const $CodeBatch = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-03-17T12:53:08.629Z'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ],
            example: '2025-03-17T12:53:08.629Z'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    nullable: true
                },
                {
                    type: 'string'
                },
                {
                    nullable: true
                }
            ]
        },
        edition: {
            type: 'string',
            example: 'ABC123XYZ'
        },
        total_generated_codes: {
            type: 'number',
            example: 1000
        },
        generated_by_id: {
            type: 'number',
            example: 1
        }
    },
    required: ['id', 'created_at', 'updated_at', 'deleted_at', 'edition', 'total_generated_codes', 'generated_by_id']
} as const;