// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
  GetCodeBatchesSearchData,
  GetCodeBatchesSearchResponse,
  GetCodesSearchData,
  GetCodesSearchResponse,
  PostCodesGenerateData,
  PostCodesGenerateResponse,
  PostCodesValidateData,
  PostCodesValidateResponse,
} from './types.gen';

/**
 * Search code batches
 * Search for code batches.
 * @param data The data for the request.
 * @param data.limit
 * @param data.page
 * @param data.orderBy
 * @param data.includeArchived
 * @param data.search
 * @param data.codeBatchId
 * @param data.sortBy
 * @returns unknown Code batches retrieved successfully
 * @throws ApiError
 */
export const getCodeBatchesSearch = (
  data: GetCodeBatchesSearchData = {}
): CancelablePromise<GetCodeBatchesSearchResponse> => {
  return __request(OpenAPI, {
    method: 'GET',
    url: '/code-batches/search',
    query: {
      limit: data.limit,
      page: data.page,
      order_by: data.orderBy,
      include_archived: data.includeArchived,
      search: data.search,
      code_batch_id: data.codeBatchId,
      sort_by: data.sortBy,
    },
  });
};

/**
 * Search codes
 * Search for codes.
 * @param data The data for the request.
 * @param data.limit
 * @param data.page
 * @param data.orderBy
 * @param data.includeArchived
 * @param data.search
 * @param data.codeBatchId
 * @param data.sortBy
 * @returns unknown Codes retrieved successfully
 * @throws ApiError
 */
export const getCodesSearch = (
  data: GetCodesSearchData = {}
): CancelablePromise<GetCodesSearchResponse> => {
  return __request(OpenAPI, {
    method: 'GET',
    url: '/codes/search',
    query: {
      limit: data.limit,
      page: data.page,
      order_by: data.orderBy,
      include_archived: data.includeArchived,
      search: data.search,
      code_batch_id: data.codeBatchId,
      sort_by: data.sortBy,
    },
  });
};

/**
 * Generate codes
 * Generate codes for a given edition.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns CodeBatch Codes generated successfully
 * @throws ApiError
 */
export const postCodesGenerate = (
  data: PostCodesGenerateData = {}
): CancelablePromise<PostCodesGenerateResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/codes/generate',
    body: data.requestBody,
    mediaType: 'application/json',
  });
};

/**
 * Validate code
 * Validate a code.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Code Code validated successfully
 * @throws ApiError
 */
export const postCodesValidate = (
  data: PostCodesValidateData = {}
): CancelablePromise<PostCodesValidateResponse> => {
  return __request(OpenAPI, {
    method: 'POST',
    url: '/codes/validate',
    body: data.requestBody,
    mediaType: 'application/json',
  });
};
