// This file is auto-generated by @hey-api/openapi-ts

export type Code = {
  id: string;
  created_at: string | null | string | unknown;
  updated_at: string | null | string | unknown;
  deleted_at: string | null | string | unknown;
  code: string;
  code_used_at: string | null | string | unknown;
  code_batch_id: string;
  code_used_by_id: number | null;
};

export type CodeBatch = {
  id: string;
  created_at: string | null | string | unknown;
  updated_at: string | null | string | unknown;
  deleted_at: string | null | string | unknown;
  edition: string;
  total_generated_codes: number;
  generated_by_id: number;
};

export type GetCodeBatchesSearchData = {
  codeBatchId?: string;
  includeArchived?: 'true' | 'false';
  limit?: number | null;
  orderBy?: 'asc' | 'desc';
  page?: number | null;
  search?: string;
  sortBy?:
    | 'id'
    | 'created_at'
    | 'updated_at'
    | 'deleted_at'
    | 'edition'
    | 'total_generated_codes'
    | 'generated_by_id';
};

export type GetCodeBatchesSearchResponse = {
  total_pages: number;
  current_page: number;
  next_page: number | null;
  previous_page: number | null;
  records: Array<CodeBatch>;
  total_records: number;
};

export type GetCodesSearchData = {
  codeBatchId?: string;
  includeArchived?: 'true' | 'false';
  limit?: number | null;
  orderBy?: 'asc' | 'desc';
  page?: number | null;
  search?: string;
  sortBy?:
    | 'id'
    | 'created_at'
    | 'updated_at'
    | 'deleted_at'
    | 'code'
    | 'code_used_at'
    | 'code_batch_id'
    | 'code_used_by_id';
};

export type GetCodesSearchResponse = {
  total_pages: number;
  current_page: number;
  next_page: number | null;
  previous_page: number | null;
  records: Array<Code>;
  total_records: number;
};

export type PostCodesGenerateData = {
  requestBody?: {
    edition: string;
    count: number;
  };
};

export type PostCodesGenerateResponse = CodeBatch;

export type PostCodesValidateData = {
  requestBody?: {
    code: string;
  };
};

export type PostCodesValidateResponse = Code;

export type $OpenApiTs = {
  '/code-batches/search': {
    get: {
      req: GetCodeBatchesSearchData;
      res: {
        /**
         * Code batches retrieved successfully
         */
        200: {
          total_pages: number;
          current_page: number;
          next_page: number | null;
          previous_page: number | null;
          records: Array<CodeBatch>;
          total_records: number;
        };
      };
    };
  };
  '/codes/search': {
    get: {
      req: GetCodesSearchData;
      res: {
        /**
         * Codes retrieved successfully
         */
        200: {
          total_pages: number;
          current_page: number;
          next_page: number | null;
          previous_page: number | null;
          records: Array<Code>;
          total_records: number;
        };
      };
    };
  };
  '/codes/generate': {
    post: {
      req: PostCodesGenerateData;
      res: {
        /**
         * Codes generated successfully
         */
        201: CodeBatch;
      };
    };
  };
  '/codes/validate': {
    post: {
      req: PostCodesValidateData;
      res: {
        /**
         * Code validated successfully
         */
        200: Code;
      };
    };
  };
};
