export const E3_SCALES = [
  'Proactivity',
  'Dominance',
  'Endurance',
  'Order',
  'Support',
  'Networking',
  'Exhibition',
  'Autonomy',
  'Aggression',
  'Change',
  'Emotional Support',
  'Self-Critical',
  'Submissiveness',
  'Self-Control',
  'Self-Confidence',
  'Personal Adjustment',
  'Creativity',
  'Military Leadership',
  'Criticality',
  'Mentoring',
  'Free Spirit',
] as const;
