import shuffle from 'lodash/shuffle';

export const ADJECTIVES = {
  1: { en: 'Inattentive', es: 'Desatento' },
  2: { en: 'Active', es: 'Activo' },
  3: { en: 'Adaptable', es: 'Adaptable' },
  4: { en: 'Adventurous', es: 'Aventurero' },
  5: { en: 'Impressionable', es: 'Impresionable' },
  6: { en: 'Affectionate', es: 'Afectuoso' },
  7: { en: 'Aggressive', es: 'Agresivo' },
  8: { en: 'Alert', es: 'Alerta' },
  9: { en: 'Emotionally Distant', es: 'Emocionalmente Distante' },
  10: { en: 'Ambitious', es: 'Ambicioso' },
  11: { en: 'Anxious', es: 'Ansioso' },
  12: { en: 'Apathetic', es: 'Apático' },
  13: { en: 'Appreciative', es: 'Agradecido' },
  14: { en: 'Argumentative', es: 'Argumentativo' },
  15: { en: 'Arrogant', es: 'Arrogante' },
  16: { en: 'Artistic', es: 'Artístico' },
  17: { en: 'Assertive', es: 'Asertivo' },
  18: { en: 'Attractive', es: 'Atractivo' },
  19: { en: 'Authoritarian', es: 'Autoritario' },
  20: { en: 'Awkward', es: 'Torpe' },
  21: { en: 'Bitter', es: 'Amargado' },
  22: { en: 'Bullying', es: 'Abusivo' },
  23: { en: 'Bragging', es: 'Jactancioso' },
  24: { en: 'Bossy', es: 'Mandón' },
  25: { en: 'Calm', es: 'Calmado' },
  26: { en: 'Capable', es: 'Capaz' },
  27: { en: 'Careless', es: 'Descuidado' },
  28: { en: 'Cautious', es: 'Cauteloso' },
  29: { en: 'Changeable', es: 'Cambiante' },
  30: { en: 'Charming', es: 'Encantador' },
  31: { en: 'Cheerful', es: 'Alegre' },
  32: { en: 'Civilized', es: 'Civilizado' },
  33: { en: 'Clear Thinking', es: 'De pensamiento claro' },
  34: { en: 'Clever', es: 'Inteligente' },
  35: { en: 'Harsh', es: 'Severo' },
  36: { en: 'Detached or Aloof', es: 'Distante' },
  37: { en: 'Commonplace', es: 'Común' },
  38: { en: 'Complaining', es: 'Quejoso' },
  39: { en: 'Complicated', es: 'Complicado' },
  40: { en: 'Conceited', es: 'Engreído' },
  41: { en: 'Confident', es: 'Confiado' },
  42: { en: 'Confused', es: 'Confundido' },
  43: { en: 'Conscientious', es: 'Consciente' },
  44: { en: 'Conservative', es: 'Conservador' },
  45: { en: 'Considerate', es: 'Considerado' },
  46: { en: 'Contented', es: 'Contento' },
  47: { en: 'Conventional', es: 'Convencional' },
  48: { en: 'Composed', es: 'Comedido' },
  49: { en: 'Cooperative', es: 'Cooperativo' },
  50: { en: 'Courageous', es: 'Valiente' },
  51: { en: 'Cowardly', es: 'Cobarde' },
  52: { en: 'Cruel', es: 'Cruel' },
  53: { en: 'Curious', es: 'Curioso' },
  54: { en: 'Cynical', es: 'Cínico' },
  55: { en: 'Daring', es: 'Audaz' },
  56: { en: 'Lying', es: 'Mentiroso' },
  57: { en: 'Defensive', es: 'Defensivo' },
  58: { en: 'Deliberate', es: 'Deliberado' },
  59: { en: 'Demanding', es: 'Exigente' },
  60: { en: 'Dependable', es: 'Fiable' },
  61: { en: 'Dependent', es: 'Dependiente' },
  62: { en: 'Hopeless', es: 'Desesperanzado' },
  63: { en: 'Determined', es: 'Decidido' },
  64: { en: 'Dignified', es: 'Digno' },
  65: { en: 'Discreet', es: 'Discreto' },
  66: { en: 'Disorderly', es: 'Desordenado' },
  67: { en: 'Dissatisfied', es: 'Insatisfecho' },
  68: { en: 'Distractible', es: 'Distraído' },
  69: { en: 'Distrustful', es: 'Desconfiado' },
  70: { en: 'Dominant', es: 'Dominante' },
  71: { en: 'Dreamy', es: 'Soñador' },
  72: { en: 'Dull', es: 'Aburrido' },
  73: { en: 'Easy Going', es: 'De trato fácil' },
  74: { en: 'Effeminate', es: 'Afeminado' },
  75: { en: 'Efficient', es: 'Eficiente' },
  76: { en: 'Egotistical', es: 'Egocéntrico' },
  77: { en: 'Emotional', es: 'Emocional' },
  78: { en: 'Energetic', es: 'Energético' },
  79: { en: 'Enterprising', es: 'Emprendedor' },
  80: { en: 'Enthusiastic', es: 'Entusiasta' },
  81: { en: 'Vague', es: 'Vago' },
  82: { en: 'Excitable', es: 'Excitable' },
  83: { en: 'Fair Minded', es: 'Justo' },
  84: { en: 'Fault Finding', es: 'Crítico' },
  85: { en: 'Fearful', es: 'Temeroso' },
  86: { en: 'Feminine', es: 'Femenino' },
  87: { en: 'Erratic', es: 'Errático' },
  88: { en: 'Flirtatious', es: 'Coqueto' },
  89: { en: 'Foolish', es: 'Tonto' },
  90: { en: 'Forceful', es: 'Enérgico' },
  91: { en: 'Foresighted', es: 'Previsor' },
  92: { en: 'Forgetful', es: 'Olvidadizo' },
  93: { en: 'Forgiving', es: 'Perdonador' },
  94: { en: 'Formal', es: 'Formal' },
  95: { en: 'Straightforward', es: 'Directo' },
  96: { en: 'Friendly', es: 'Amigable' },
  97: { en: 'Air-Headed', es: 'Cabeza de aire' },
  98: { en: 'Fussy', es: 'Quisquilloso' },
  99: { en: 'Generous', es: 'Generoso' },
  100: { en: 'Gentle', es: 'Amable' },
  101: { en: 'Gloomy', es: 'Sombrío' },
  102: { en: 'Good Looking', es: 'Atractivo' },
  103: { en: 'Good Natured', es: 'Buen carácter' },
  104: { en: 'Greedy', es: 'Codicioso' },
  105: { en: 'Handsome', es: 'Guapo' },
  106: { en: 'Hard Headed', es: 'Cabezón' },
  107: { en: 'Hard Hearted', es: 'Insensible' },
  108: { en: 'Hasty', es: 'Apresurado' },
  109: { en: 'Headstrong', es: 'Obstinado' },
  110: { en: 'Healthy', es: 'Saludable' },
  111: { en: 'Helpful', es: 'Servicial' },
  112: { en: 'High Strung', es: 'Nervioso' },
  113: { en: 'Honest', es: 'Honesto' },
  114: { en: 'Hostile', es: 'Hostil' },
  115: { en: 'Humorous', es: 'Humorístico' },
  116: { en: 'Hurried', es: 'Apurado' },
  117: { en: 'Idealistic', es: 'Idealista' },
  118: { en: 'Imaginative', es: 'Imaginativo' },
  119: { en: 'Immature', es: 'Inmaduro' },
  120: { en: 'Impatient', es: 'Impaciente' },
  121: { en: 'Impulsive', es: 'Impulsivo' },
  122: { en: 'Independent', es: 'Independiente' },
  123: { en: 'Indifferent', es: 'Indiferente' },
  124: { en: 'Individualistic', es: 'Individualista' },
  125: { en: 'Industrious', es: 'Laborioso' },
  126: { en: 'Childish', es: 'Infantil' },
  127: { en: 'Informal', es: 'Informal' },
  128: { en: 'Ingenious', es: 'Ingenioso' },
  129: { en: 'Repressed', es: 'Reprimido' },
  130: { en: 'Initiative', es: 'Iniciativa' },
  131: { en: 'Insightful', es: 'Perspicaz' },
  132: { en: 'Intelligent', es: 'Inteligente' },
  133: { en: 'Limited Interests', es: 'Intereses limitados' },
  134: { en: 'Broad Interests', es: 'Intereses amplios' },
  135: { en: 'Intolerant', es: 'Intolerante' },
  136: { en: 'Inventive', es: 'Inventivo' },
  137: { en: 'Irresponsible', es: 'Irresponsable' },
  138: { en: 'Irritable', es: 'Irritable' },
  139: { en: 'Jolly', es: 'Alegre' },
  140: { en: 'Kind', es: 'Amable' },
  141: { en: 'Lazy', es: 'Perezoso' },
  142: { en: 'Leisurely', es: 'Tranquilo' },
  143: { en: 'Logical', es: 'Lógico' },
  144: { en: 'Loud', es: 'Ruidoso' },
  145: { en: 'Loyal', es: 'Leal' },
  146: { en: 'Polite', es: 'Cortés' },
  147: { en: 'Masculine', es: 'Masculino' },
  148: { en: 'Mature', es: 'Maduro' },
  149: { en: 'Compliant', es: 'Conformista' },
  150: { en: 'Methodical', es: 'Metódico' },
  151: { en: 'Mild', es: 'Suave' },
  152: { en: 'Mischievous', es: 'Travieso' },
  153: { en: 'Moderate', es: 'Moderado' },
  154: { en: 'Modest', es: 'Modesto' },
  155: { en: 'Moody', es: 'Temperamental' },
  156: { en: 'Nagging', es: 'Criticón' },
  157: { en: 'Natural', es: 'Natural' },
  158: { en: 'Nervous', es: 'Nervioso' },
  159: { en: 'Noisy', es: 'Ruidoso' },
  160: { en: 'Accommodating', es: 'Servicial' },
  161: { en: 'Obnoxious', es: 'Desagradable' },
  162: { en: 'Opinionated', es: 'Terco' },
  163: { en: 'Opportunistic', es: 'Oportunista' },
  164: { en: 'Optimistic', es: 'Optimista' },
  165: { en: 'Organized', es: 'Organizado' },
  166: { en: 'Original', es: 'Original' },
  167: { en: 'Outgoing', es: 'Extrovertido' },
  168: { en: 'Outspoken', es: 'Franco' },
  169: { en: 'Painstaking', es: 'Minucioso' },
  170: { en: 'Patient', es: 'Paciente' },
  171: { en: 'Peaceful', es: 'Pacífico' },
  172: { en: 'Odd', es: 'Extraño' },
  173: { en: 'Persevering', es: 'Perseverante' },
  174: { en: 'Persistent', es: 'Persistente' },
  175: { en: 'Pessimistic', es: 'Pesimista' },
  176: { en: 'Planner', es: 'Planificador' },
  177: { en: 'Pleasant', es: 'Agradable' },
  178: { en: 'Pleasure Seeking', es: 'Hedonista' },
  179: { en: 'Poised', es: 'Elegante' },
  180: { en: 'Polished', es: 'Pulido' },
  181: { en: 'Practical', es: 'Práctico' },
  182: { en: 'Praising', es: 'Elogioso' },
  183: { en: 'Precise', es: 'Preciso' },
  184: { en: 'Prejudiced', es: 'Prejuicioso' },
  185: { en: 'Preoccupied', es: 'Preocupado' },
  186: { en: 'Progressive', es: 'Progresista' },
  187: { en: 'Prudish', es: 'Mojigato' },
  188: { en: 'Quarrelsome', es: 'Pendenciero' },
  189: { en: 'Quick', es: 'Rápido' },
  190: { en: 'Quiet', es: 'Tranquilo' },
  191: { en: 'Quirky', es: 'Peculiar' },
  192: { en: 'Quitting', es: 'Rendido' },
  193: { en: 'Rational', es: 'Racional' },
  194: { en: 'Scatter-Brained', es: 'Despistado' },
  195: { en: 'Realistic', es: 'Realista' },
  196: { en: 'Reasonable', es: 'Razonable' },
  197: { en: 'Rebellious', es: 'Rebelde' },
  198: { en: 'Reckless', es: 'Imprudente' },
  199: { en: 'Reflective', es: 'Reflexivo' },
  200: { en: 'Relaxed', es: 'Relajado' },
  201: { en: 'Reliable', es: 'Confiable' },
  202: { en: 'Resentful', es: 'Resentido' },
  203: { en: 'Reserved', es: 'Reservado' },
  204: { en: 'Resourceful', es: 'Ingenioso' },
  205: { en: 'Responsible', es: 'Responsable' },
  206: { en: 'Restless', es: 'Inquieto' },
  207: { en: 'Unassertive', es: 'Poco asertivo' },
  208: { en: 'Rigid', es: 'Rígido' },
  209: { en: 'Robust', es: 'Robusto' },
  210: { en: 'Rude', es: 'Grosero' },
  211: { en: 'Sarcastic', es: 'Sarcástico' },
  212: { en: 'Self Centered', es: 'Egocéntrico' },
  213: { en: 'Self Confident', es: 'Seguro de sí mismo' },
  214: { en: 'Self Controlled', es: 'Autocontrolado' },
  215: { en: 'Self Denying', es: 'Abnegado' },
  216: { en: 'Self Pitying', es: 'Autocompasivo' },
  217: { en: 'Self Punishing', es: 'Autocastigador' },
  218: { en: 'Self Seeking', es: 'Interesado' },
  219: { en: 'Selfish', es: 'Egoísta' },
  220: { en: 'Sensitive', es: 'Sensible' },
  221: { en: 'Sentimental', es: 'Sentimental' },
  222: { en: 'Serious', es: 'Serio' },
  223: { en: 'Severe', es: 'Severo' },
  224: { en: 'Sexy', es: 'Sexy' },
  225: { en: 'Shallow', es: 'Superficial' },
  226: { en: 'Sharp Witted', es: 'Agudo' },
  227: { en: 'Lacks Initiative', es: 'Falta de iniciativa' },
  228: { en: 'Show Off', es: 'Presumido' },
  229: { en: 'Smart', es: 'Inteligente' },
  230: { en: 'Shy', es: 'Tímido' },
  231: { en: 'Silent', es: 'Silencioso' },
  232: { en: 'Simple', es: 'Sencillo' },
  233: { en: 'Sincere', es: 'Sincero' },
  234: { en: 'Sloppy', es: 'Descuidado' },
  235: { en: 'Slow', es: 'Lento' },
  236: { en: 'Cunning', es: 'Astuto' },
  237: { en: 'Smug', es: 'Complaciente' },
  238: { en: 'Snobbish', es: 'Esnob' },
  239: { en: 'Sociable', es: 'Sociable' },
  240: { en: 'Soft Hearted', es: 'Tierno' },
  241: { en: 'Sophisticated', es: 'Sofisticado' },
  242: { en: 'Tightwad', es: 'Tacaño' },
  243: { en: 'Spineless', es: 'Sin espinas' },
  244: { en: 'Spontaneous', es: 'Espontáneo' },
  245: { en: 'Spunky', es: 'Enérgico' },
  246: { en: 'Stable', es: 'Estable' },
  247: { en: 'Steady', es: 'Constante' },
  248: { en: 'Stern', es: 'Severo' },
  249: { en: 'Stingy', es: 'Tacaño' },
  250: { en: 'Emotionless', es: 'Sin emoción' },
  251: { en: 'Strong', es: 'Fuerte' },
  252: { en: 'Stubborn', es: 'Terco' },
  253: { en: 'Submissive', es: 'Sumiso' },
  254: { en: 'Gullible', es: 'Crédulo' },
  255: { en: 'Depressed', es: 'Deprimido' },
  256: { en: 'Superstitious', es: 'Supersticioso' },
  257: { en: 'Suspicious', es: 'Sospechoso' },
  258: { en: 'Sympathetic', es: 'Compasivo' },
  259: { en: 'Tactful', es: 'Tacto' },
  260: { en: 'Tactless', es: 'Falto de tacto' },
  261: { en: 'Talkative', es: 'Hablador' },
  262: { en: 'Temperamental', es: 'Temperamental' },
  263: { en: 'Tense', es: 'Tenso' },
  264: { en: 'Thankless', es: 'Ingrato' },
  265: { en: 'Thorough', es: 'Minucioso' },
  266: { en: 'Thoughtful', es: 'Pensativo' },
  267: { en: 'Thrifty', es: 'Ahorrativo' },
  268: { en: 'Timid', es: 'Tímido' },
  269: { en: 'Tolerant', es: 'Tolerante' },
  270: { en: 'Touchy', es: 'Susceptible' },
  271: { en: 'Tough', es: 'Duro' },
  272: { en: 'Trusting', es: 'Confiable' },
  273: { en: 'Unselfconscious', es: 'Desinhibido' },
  274: { en: 'Unambitious', es: 'Poco ambicioso' },
  275: { en: 'Humble', es: 'Humilde' },
  276: { en: 'Unconventional', es: 'No convencional' },
  277: { en: 'Undependable', es: 'Poco fiable' },
  278: { en: 'Understanding', es: 'Comprensivo' },
  279: { en: 'Unemotional', es: 'Inexpresivo' },
  280: { en: 'Unexcitable', es: 'Imperturbable' },
  281: { en: 'Unfriendly', es: 'Antipático' },
  282: { en: 'Uninhibited', es: 'Desinhibido' },
  283: { en: 'Unintelligent', es: 'Poco inteligente' },
  284: { en: 'Unkind', es: 'Descortés' },
  285: { en: 'Unrealistic', es: 'Poco realista' },
  286: { en: 'Neglectful', es: 'Descuidado' },
  287: { en: 'Unselfish', es: 'Altruista' },
  288: { en: 'Unstable', es: 'Inestable' },
  289: { en: 'Versatile', es: 'Versátil' },
  290: { en: 'Spiteful', es: 'Rencoroso' },
  291: { en: 'Warm', es: 'Cálido' },
  292: { en: 'Wary', es: 'Cauteloso' },
  293: { en: 'Weak', es: 'Débil' },
  294: { en: 'Whiny', es: 'Quejoso' },
  295: { en: 'Wholesome', es: 'Saludable' },
  296: { en: 'Wise', es: 'Sabio' },
  297: { en: 'Withdrawn', es: 'Retraído' },
  298: { en: 'Witty', es: 'Ingenioso' },
  299: { en: 'Worrying', es: 'Preocupante' },
  300: { en: 'Zany', es: 'Estrafalario' },
} as const;

export const HIDDEN_ADJECTIVES: string[] = [
  '64', // Dignified
  '117', // Idealistic
  '189', // Quick
  '191', // Quirky
  '223', // Severe
  '224', // Sexy
  '229', // Smart
  '235', // Slow
  '237', // Smug
  '242', // Tightwad
  '280', // Unexcitable
  '292', // Wary
] as const;

export const ADJECTIVES_WITHOUT_HIDDEN = Object.entries(ADJECTIVES).filter(([adjectiveNumber]) => {
  return !HIDDEN_ADJECTIVES.includes(adjectiveNumber);
});

export function getShuffledAdjectives() {
  return shuffle(ADJECTIVES_WITHOUT_HIDDEN).map(([adjectiveNumber, value]) => [
    adjectiveNumber,
    value,
  ]) as [string, { en: string; es: string }][];
}
